import tabs from "./components/TabsComponent";

@Entry
@Component
struct Index {
  @State message: string = 'Hello World'
  // aaa aaa aaa  wwwdaw
  build() {
    // Row() {
    //   Column() {
    //     Text(this.message)
    //       .fontSize(50)
    //       .fontWeight(FontWeight.Bold)
    //     Text("上传分支测试")
    //       .fontSize(50)
    //       .fontWeight(FontWeight.Bold)
    //   }
    //   .width('100%')
    //   //新测试git——lhl
    // }
    // .height('100%')

  }
}